baseURL: http://localhost
projectName: EcoTrain
env:
  HOSTIP: http://10.192.54.37

scenarios:
  - name: Consulter la page d'accueil
    path: ./scenarios/consult_index.js
  - name: Consulter des résultats de recherche
    path: ./scenarios/consult_results.js
containers:
  - ecotrain-static_hosting-1
